# Generated by Django 5.0.6 on 2025-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0042_leadinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='LeadName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
